name: pre-commit
on:
  # Trigger the workflow on push or pull request,
  # but only for the master and dev branches
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install and run pre-commit hooks
        uses: pre-commit/action@v3.0.1
